---
name: Pipeline - REUSE Compliance Check

on: [ push, pull_request ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkou@
    - name: REUSE Version
      uses: fsfe/reuse-action@
      with:
        args: -- version

    - name: REUSE Lint
      uses: fsfe/reuse-action@
      with:
        args: --include-submodules lint

    - name: REUSE SPDX SBOM
      uses: fsfe/reuse-action@
      with:
        args: spdx
